baseURL = 'https://blog.dsnb.cc'
defaultContentLanguage = "zh"
languageCode = 'zh-Hans'
title = "DongShaoNB's Blog"
theme = "dream"

enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true

[markup]
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['\[', '\]'], ['$$', '$$']]
inline = [['\(', '\)']]
[markup.highlight]
noClasses = false

[params]
lightTheme = "emerald"
darkTheme = "forest"

author = "DongShaoNB"
description = "东少的笔记本"
avatar = "avatar.jpg"
headerTitle = "DongShaoNB's Blog"
motto = "喜欢就坚持下去吧！"

rss = true

email = "i@dsnb.cc"

siteStartYear = 2024

favicon = 'favicon.png'

customSyntaxHighlighting = true

stickyNav = true
reorderNavItems = [
    "about",
    "search",
    "github",
    "categories",
    "tags",
    "posts",
    "rss",
]
collapseNavItems = ["categories", "tags", "posts", "rss"]
# noDefaultSummaryCover = true
showTableOfContents = true
showSummaryCoverInPost = true
imageZoomableInPost = true
showPrevNextPost = true

[params.twikoo]
enabled = true
envID = "https://dsblog-twikoo.netlify.app/.netlify/functions/twikoo"
region = ""
lang = "zh-CN"

[params.navItems]
github = { href = "https://github.com/DS-Pages/Blog", target = "_blank", icon = "logo-github", title = "GitHub" }

[params.experimental]
jsDate = true
jsDateFormat = "yyyy 年 MM 月 dd 日"
